version: 2
updates:
  - package-ecosystem: "github-actions" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "node" 
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
